import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

type Language = "fr" | "ar";

type Translations = {
  [key: string]: {
    fr: string;
    ar: string;
  };
};

const translations: Translations = {
  appName: { fr: "FAYAGE", ar: "فاياج" },
  welcome: { fr: "Bienvenue", ar: "مرحبا" },
  login: { fr: "Connexion", ar: "تسجيل الدخول" },
  signup: { fr: "Inscription", ar: "إنشاء حساب" },
  phone: { fr: "Numéro de téléphone", ar: "رقم الهاتف" },
  password: { fr: "Mot de passe", ar: "كلمة المرور" },
  email: { fr: "Email", ar: "البريد الإلكتروني" },
  fullName: { fr: "Nom complet", ar: "الاسم الكامل" },
  client: { fr: "Client", ar: "عميل" },
  driver: { fr: "Chauffeur", ar: "سائق" },
  selectRole: { fr: "Choisir votre rôle", ar: "اختر دورك" },
  continueAs: { fr: "Continuer en tant que", ar: "المتابعة ك" },
  home: { fr: "Accueil", ar: "الرئيسية" },
  track: { fr: "Suivi", ar: "تتبع" },
  history: { fr: "Historique", ar: "السجل" },
  profile: { fr: "Profil", ar: "الملف الشخصي" },
  jobs: { fr: "Missions", ar: "المهام" },
  active: { fr: "En cours", ar: "نشط" },
  earnings: { fr: "Gains", ar: "الأرباح" },
  createRequest: { fr: "Créer une demande", ar: "إنشاء طلب" },
  newTransportRequest: { fr: "Nouvelle demande de transport", ar: "طلب نقل جديد" },
  pickup: { fr: "Point de ramassage", ar: "نقطة الاستلام" },
  delivery: { fr: "Point de livraison", ar: "نقطة التسليم" },
  vehicleType: { fr: "Type de véhicule", ar: "نوع المركبة" },
  goodsDescription: { fr: "Description des marchandises", ar: "وصف البضائع" },
  goodsPhotos: { fr: "Photos des marchandises", ar: "صور البضائع" },
  estimatedWeight: { fr: "Poids estimé (kg)", ar: "الوزن التقريبي (كغ)" },
  deliveryOption: { fr: "Option de livraison", ar: "خيار التوصيل" },
  standard: { fr: "Standard", ar: "عادي" },
  urgent: { fr: "Urgent", ar: "عاجل" },
  express: { fr: "Express", ar: "سريع" },
  estimatedPrice: { fr: "Prix estimé", ar: "السعر التقديري" },
  customPrice: { fr: "Prix personnalisé", ar: "سعر مخصص" },
  setCustomPrice: { fr: "Définir un prix personnalisé", ar: "تحديد سعر مخصص" },
  photoOfGoods: { fr: "Photo des marchandises", ar: "صورة البضائع" },
  takePhoto: { fr: "Prendre une photo", ar: "التقاط صورة" },
  choosePhoto: { fr: "Choisir une photo", ar: "اختيار صورة" },
  photoOptional: { fr: "Optionnel - Ajoutez une photo de vos marchandises", ar: "اختياري - أضف صورة لبضائعك" },
  photoOptionalMultiple: { fr: "Optionnel - Ajoutez jusqu'à 5 photos de vos marchandises", ar: "اختياري - أضف حتى 5 صور لبضائعك" },
  paymentMethod: { fr: "Mode de paiement", ar: "طريقة الدفع" },
  cashToDriver: { fr: "Paiement en espèces au chauffeur à la livraison", ar: "الدفع نقداً للسائق عند التسليم" },
  paymentUndertaking: { fr: "Je m'engage à payer le montant convenu au chauffeur à la livraison", ar: "أتعهد بدفع المبلغ المتفق عليه للسائق عند التسليم" },
  undertakingRequired: { fr: "Vous devez accepter les conditions de paiement", ar: "يجب قبول شروط الدفع" },
  reviewOrder: { fr: "Vérifier la commande", ar: "مراجعة الطلب" },
  orderConfirmation: { fr: "Confirmation de commande", ar: "تأكيد الطلب" },
  reviewBeforeConfirm: { fr: "Vérifiez les détails avant de confirmer", ar: "تحقق من التفاصيل قبل التأكيد" },
  from: { fr: "De", ar: "من" },
  to: { fr: "À", ar: "إلى" },
  deliveryTime: { fr: "Heure de livraison", ar: "وقت التسليم" },
  price: { fr: "Prix", ar: "السعر" },
  modify: { fr: "Modifier", ar: "تعديل" },
  confirmOrder: { fr: "Confirmer la commande", ar: "تأكيد الطلب" },
  submit: { fr: "Envoyer", ar: "إرسال" },
  cancel: { fr: "Annuler", ar: "إلغاء" },
  accept: { fr: "Accepter", ar: "قبول" },
  reject: { fr: "Refuser", ar: "رفض" },
  negotiate: { fr: "Négocier", ar: "تفاوض" },
  proposedPrice: { fr: "Prix proposé", ar: "السعر المقترح" },
  yourOffer: { fr: "Votre offre", ar: "عرضك" },
  distance: { fr: "Distance", ar: "المسافة" },
  rating: { fr: "Note", ar: "التقييم" },
  verified: { fr: "Vérifié", ar: "موثق" },
  noActiveRequests: { fr: "Aucune demande active", ar: "لا توجد طلبات نشطة" },
  noActiveDeliveries: { fr: "Aucune livraison active", ar: "لا توجد عمليات توصيل نشطة" },
  noAvailableJobs: { fr: "Aucune mission disponible", ar: "لا توجد مهام متاحة" },
  noDeliveryHistory: { fr: "Aucun historique de livraison", ar: "لا يوجد سجل توصيل" },
  startCreatingRequest: { fr: "Créez votre première demande de transport", ar: "أنشئ طلب النقل الأول" },
  waitingForJobs: { fr: "En attente de nouvelles missions", ar: "في انتظار مهام جديدة" },
  jobsNearYou: { fr: "missions près de vous", ar: "مهام بالقرب منك" },
  availableJobs: { fr: "Missions disponibles", ar: "المهام المتاحة" },
  stayInBusyAreas: { fr: "Restez dans les zones actives", ar: "ابق في المناطق النشطة" },
  viewMap: { fr: "Voir carte", ar: "عرض الخريطة" },
  orderManagement: { fr: "Gestion des commandes", ar: "إدارة الطلبات" },
  searchOrders: { fr: "Rechercher...", ar: "بحث..." },
  noResultsFound: { fr: "Aucun résultat", ar: "لا توجد نتائج" },
  noOrders: { fr: "Aucune commande", ar: "لا توجد طلبات" },
  orders: { fr: "Commandes", ar: "الطلبات" },
  stayInBusyAreasDesc: { fr: "Plus de missions dans les zones commerciales", ar: "المزيد من المهام في المناطق التجارية" },
  notificationsEnabled: { fr: "Restez connecté", ar: "ابق متصلاً" },
  notificationsEnabledDesc: { fr: "Vous serez notifié des nouvelles missions", ar: "سيتم إعلامك بالمهام الجديدة" },
  completeDeliveries: { fr: "Effectuez des livraisons pour voir l'historique", ar: "أكمل عمليات التوصيل لرؤية السجل" },
  driverOnTheWay: { fr: "Chauffeur en route", ar: "السائق في الطريق" },
  driverArrived: { fr: "Chauffeur arrivé", ar: "وصل السائق" },
  driverHasArrived: { fr: "Le chauffeur est arrivé!", ar: "وصل السائق!" },
  iHaveArrived: { fr: "Je suis arrivé", ar: "لقد وصلت" },
  isWaitingForYou: { fr: "vous attend", ar: "ينتظرك" },
  goodsPickedUp: { fr: "Marchandises récupérées", ar: "تم استلام البضائع" },
  inTransit: { fr: "En transit", ar: "في الطريق" },
  delivered: { fr: "Livré", ar: "تم التسليم" },
  pending: { fr: "En attente", ar: "قيد الانتظار" },
  accepted: { fr: "Accepté", ar: "مقبول" },
  completed: { fr: "Terminé", ar: "مكتمل" },
  cancelled: { fr: "Annulé", ar: "ملغى" },
  settings: { fr: "Paramètres", ar: "الإعدادات" },
  language: { fr: "Langue", ar: "اللغة" },
  notifications: { fr: "Notifications", ar: "الإشعارات" },
  account: { fr: "Compte", ar: "الحساب" },
  logout: { fr: "Déconnexion", ar: "تسجيل الخروج" },
  verification: { fr: "Vérification", ar: "التحقق" },
  nationalId: { fr: "Carte d'identité nationale (CIN)", ar: "بطاقة الهوية الوطنية" },
  nationalIdNumber: { fr: "Numéro CIN", ar: "رقم بطاقة الهوية" },
  cinFront: { fr: "Photo CIN (recto)", ar: "صورة البطاقة (الوجه الأمامي)" },
  cinBack: { fr: "Photo CIN (verso)", ar: "صورة البطاقة (الوجه الخلفي)" },
  cinSection: { fr: "Carte d'identité nationale (CIN)", ar: "بطاقة الهوية الوطنية" },
  selfieWithCin: { fr: "Selfie avec CIN", ar: "صورة شخصية مع البطاقة" },
  selfie: { fr: "Selfie", ar: "صورة شخصية" },
  vehicleRegistration: { fr: "Carte grise", ar: "البطاقة الرمادية" },
  vehicleRegistrationSection: { fr: "Carte grise du véhicule", ar: "البطاقة الرمادية للمركبة" },
  vehicleRegistrationFront: { fr: "Carte grise (recto)", ar: "البطاقة الرمادية (الوجه الأمامي)" },
  vehicleRegistrationBack: { fr: "Carte grise (verso)", ar: "البطاقة الرمادية (الوجه الخلفي)" },
  insurance: { fr: "Assurance véhicule", ar: "تأمين المركبة" },
  drivingLicense: { fr: "Permis de conduire", ar: "رخصة القيادة" },
  drivingLicenseSection: { fr: "Permis de conduire", ar: "رخصة القيادة" },
  drivingLicenseFront: { fr: "Permis de conduire (recto)", ar: "رخصة القيادة (الوجه الأمامي)" },
  drivingLicenseBack: { fr: "Permis de conduire (verso)", ar: "رخصة القيادة (الوجه الخلفي)" },
  upload: { fr: "Télécharger", ar: "رفع" },
  uploadPhoto: { fr: "Télécharger une photo", ar: "رفع صورة" },
  profilePhotoRequired: { fr: "La photo de profil est obligatoire", ar: "صورة الملف الشخصي مطلوبة" },
  addProfilePhoto: { fr: "Ajouter une photo de profil", ar: "إضافة صورة الملف الشخصي" },
  changePhoto: { fr: "Changer la photo", ar: "تغيير الصورة" },
  photoUploaded: { fr: "Photo téléchargée", ar: "تم رفع الصورة" },
  pendingVerification: { fr: "Vérification en cours", ar: "التحقق جاري" },
  verificationComplete: { fr: "Vérification terminée", ar: "تم التحقق" },
  accountPendingVerification: { fr: "Votre compte est en attente de vérification", ar: "حسابك في انتظار التحقق" },
  cannotAcceptOrdersYet: { fr: "Vous ne pouvez pas accepter de commandes tant que votre compte n'est pas vérifié", ar: "لا يمكنك قبول الطلبات حتى يتم التحقق من حسابك" },
  rateDriver: { fr: "Noter le chauffeur", ar: "تقييم السائق" },
  rateClient: { fr: "Noter le client", ar: "تقييم العميل" },
  writeReview: { fr: "Écrire un avis", ar: "اكتب تعليقا" },
  submitReview: { fr: "Envoyer l'avis", ar: "إرسال التقييم" },
  downloadPdf: { fr: "Télécharger PDF", ar: "تحميل PDF" },
  chat: { fr: "Discussion", ar: "محادثة" },
  callNow: { fr: "Appeler maintenant", ar: "اتصل الآن" },
  callClient: { fr: "Appeler le client", ar: "اتصل بالعميل" },
  callDriver: { fr: "Appeler le chauffeur", ar: "اتصل بالسائق" },
  call: { fr: "Appeler", ar: "اتصال" },
  callConnecting: { fr: "Connexion...", ar: "جارٍ الاتصال..." },
  callRinging: { fr: "Sonnerie...", ar: "يرن..." },
  callIncoming: { fr: "Appel entrant", ar: "مكالمة واردة" },
  callEnded: { fr: "Appel terminé", ar: "انتهت المكالمة" },
  endCall: { fr: "Raccrocher", ar: "إنهاء المكالمة" },
  decline: { fr: "Refuser", ar: "رفض" },
  mute: { fr: "Muet", ar: "كتم الصوت" },
  unmute: { fr: "Réactiver", ar: "إلغاء الكتم" },
  speaker: { fr: "Haut-parleur", ar: "مكبر الصوت" },
  earpiece: { fr: "Oreillette", ar: "سماعة الأذن" },
  typeMessage: { fr: "Tapez un message...", ar: "اكتب رسالة..." },
  send: { fr: "Envoyer", ar: "إرسال" },
  mad: { fr: "MAD", ar: "درهم" },
  km: { fr: "km", ar: "كم" },
  kg: { fr: "kg", ar: "كغ" },
  enterPickup: { fr: "Entrez l'adresse de ramassage", ar: "أدخل عنوان الاستلام" },
  enterDelivery: { fr: "Entrez l'adresse de livraison", ar: "أدخل عنوان التسليم" },
  currentLocation: { fr: "Position actuelle", ar: "الموقع الحالي" },
  navigateToPickup: { fr: "Naviguer vers le ramassage", ar: "الانتقال إلى نقطة الاستلام" },
  navigateToDelivery: { fr: "Naviguer vers la livraison", ar: "الانتقال إلى نقطة التسليم" },
  openInMaps: { fr: "Ouvrir dans Maps", ar: "فتح في الخرائط" },
  describeGoods: { fr: "Décrivez vos marchandises", ar: "صف بضائعك" },
  tricycle: { fr: "Tricycle", ar: "دراجة ثلاثية" },
  van: { fr: "Fourgon", ar: "فان" },
  truck_3_5t: { fr: "Camion 3.5T", ar: "شاحنة 3.5 طن" },
  truck_10t: { fr: "Camion 10T", ar: "شاحنة 10 طن" },
  semi: { fr: "Semi-remorque", ar: "شاحنة نصف مقطورة" },
  french: { fr: "Français", ar: "الفرنسية" },
  arabic: { fr: "Arabe", ar: "العربية" },
  selectLanguage: { fr: "Choisir la langue", ar: "اختر اللغة" },
  or: { fr: "ou", ar: "أو" },
  dontHaveAccount: { fr: "Pas encore de compte ?", ar: "ليس لديك حساب؟" },
  alreadyHaveAccount: { fr: "Déjà un compte ?", ar: "لديك حساب بالفعل؟" },
  createAccount: { fr: "Créer un compte", ar: "إنشاء حساب" },
  signIn: { fr: "Se connecter", ar: "تسجيل الدخول" },
  getStarted: { fr: "Commencer", ar: "ابدأ الآن" },
  transportGoods: { fr: "Transportez vos marchandises", ar: "انقل بضائعك" },
  tagline: { fr: "Transport rapide, sécurisé et transparent", ar: "نقل سريع وآمن وشفاف" },
  activeDeliveries: { fr: "Livraisons actives", ar: "التوصيلات النشطة" },
  activeDelivery: { fr: "Livraison active", ar: "توصيل نشط" },
  recentActivity: { fr: "Activité récente", ar: "النشاط الأخير" },
  viewAll: { fr: "Voir tout", ar: "عرض الكل" },
  todayEarnings: { fr: "Gains du jour", ar: "أرباح اليوم" },
  weeklyEarnings: { fr: "Gains de la semaine", ar: "أرباح الأسبوع" },
  totalEarnings: { fr: "Revenus totaux", ar: "إجمالي الإيرادات" },
  thisMonth: { fr: "Ce mois", ar: "هذا الشهر" },
  performance: { fr: "Performance", ar: "الأداء" },
  avgPerDelivery: { fr: "Moyenne par livraison", ar: "متوسط لكل توصيل" },
  completionRate: { fr: "Taux de réalisation", ar: "معدل الإنجاز" },
  completeFirstDelivery: { fr: "Terminez votre première livraison pour commencer à gagner", ar: "أكمل أول توصيل لك لبدء الربح" },
  today: { fr: "Aujourd'hui", ar: "اليوم" },
  totalDeliveries: { fr: "Total livraisons", ar: "إجمالي التوصيلات" },
  availableNearby: { fr: "Disponible à proximité", ar: "متاح بالقرب منك" },
  support: { fr: "Support", ar: "الدعم" },
  paymentMethods: { fr: "Moyens de paiement", ar: "طرق الدفع" },
  cash: { fr: "Espèces", ar: "نقدا" },
  deleteAccount: { fr: "Supprimer le compte", ar: "حذف الحساب" },
  confirmDelete: { fr: "Confirmer la suppression", ar: "تأكيد الحذف" },
  confirmDeleteMessage: { fr: "Êtes-vous sûr de vouloir supprimer votre compte ?", ar: "هل أنت متأكد من حذف حسابك؟" },
  yes: { fr: "Oui", ar: "نعم" },
  no: { fr: "Non", ar: "لا" },
  next: { fr: "Suivant", ar: "التالي" },
  previous: { fr: "Précédent", ar: "السابق" },
  step: { fr: "Étape", ar: "خطوة" },
  of: { fr: "sur", ar: "من" },
  personalInfo: { fr: "Informations personnelles", ar: "المعلومات الشخصية" },
  documents: { fr: "Documents", ar: "المستندات" },
  vehicleInfo: { fr: "Informations véhicule", ar: "معلومات المركبة" },
  driverRegistration: { fr: "Inscription Chauffeur", ar: "تسجيل السائق" },
  requiredField: { fr: "Champ obligatoire", ar: "حقل مطلوب" },
  invalidEmail: { fr: "Email invalide", ar: "البريد الإلكتروني غير صالح" },
  invalidPhone: { fr: "Numéro de téléphone invalide", ar: "رقم الهاتف غير صالح" },
  passwordMinLength: { fr: "Le mot de passe doit contenir au moins 6 caractères", ar: "يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل" },
  pleaseUploadAllDocuments: { fr: "Veuillez télécharger tous les documents requis", ar: "يرجى رفع جميع المستندات المطلوبة" },
  selectVehicleType: { fr: "Veuillez sélectionner un type de véhicule", ar: "يرجى اختيار نوع المركبة" },
  registrationSuccess: { fr: "Inscription réussie ! Votre compte est en attente de vérification.", ar: "تم التسجيل بنجاح! حسابك في انتظار التحقق." },
  registrationFailed: { fr: "L'inscription a échoué. Veuillez réessayer.", ar: "فشل التسجيل. يرجى المحاولة مرة أخرى." },
  fillAllFields: { fr: "Veuillez remplir tous les champs", ar: "يرجى ملء جميع الحقول" },
  verifyEmail: { fr: "Vérifiez votre email", ar: "تحقق من بريدك الإلكتروني" },
  emailVerification: { fr: "Vérification email", ar: "التحقق من البريد" },
  verificationCodeSent: { fr: "Un code de vérification a été envoyé à", ar: "تم إرسال رمز التحقق إلى" },
  verificationCode: { fr: "Code de vérification", ar: "رمز التحقق" },
  verify: { fr: "Vérifier", ar: "تحقق" },
  resendCode: { fr: "Renvoyer le code", ar: "إعادة إرسال الرمز" },
  resendIn: { fr: "Renvoyer dans", ar: "إعادة الإرسال في" },
  changeEmail: { fr: "Modifier l'email", ar: "تغيير البريد الإلكتروني" },
  emailRequired: { fr: "Email requis", ar: "البريد الإلكتروني مطلوب" },
  enterVerificationCode: { fr: "Entrez le code de vérification", ar: "أدخل رمز التحقق" },
  invalidVerificationCode: { fr: "Code invalide ou expiré", ar: "رمز غير صالح أو منتهي الصلاحية" },
  verificationSendError: { fr: "Erreur lors de l'envoi du code", ar: "خطأ في إرسال الرمز" },
  verificationError: { fr: "Erreur de vérification", ar: "خطأ في التحقق" },
  invalidCode: { fr: "Code invalide", ar: "رمز غير صالح" },
  forgotPassword: { fr: "Mot de passe oublié ?", ar: "نسيت كلمة المرور؟" },
  forgotPasswordDescription: { fr: "Entrez votre email pour recevoir un code de réinitialisation", ar: "أدخل بريدك الإلكتروني لتلقي رمز إعادة التعيين" },
  sendResetCode: { fr: "Envoyer le code", ar: "إرسال الرمز" },
  verifyCode: { fr: "Vérifier le code", ar: "تحقق من الرمز" },
  codesentTo: { fr: "Un code a été envoyé à", ar: "تم إرسال رمز إلى" },
  resendCodeIn: { fr: "Renvoyer dans", ar: "إعادة الإرسال في" },
  newPassword: { fr: "Nouveau mot de passe", ar: "كلمة المرور الجديدة" },
  enterNewPassword: { fr: "Entrez votre nouveau mot de passe", ar: "أدخل كلمة المرور الجديدة" },
  confirmPassword: { fr: "Confirmer le mot de passe", ar: "تأكيد كلمة المرور" },
  resetPassword: { fr: "Réinitialiser le mot de passe", ar: "إعادة تعيين كلمة المرور" },
  passwordRequired: { fr: "Mot de passe requis", ar: "كلمة المرور مطلوبة" },
  passwordTooShort: { fr: "Le mot de passe doit contenir au moins 6 caractères", ar: "يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل" },
  passwordMismatch: { fr: "Les mots de passe ne correspondent pas", ar: "كلمات المرور غير متطابقة" },
  passwordResetSuccess: { fr: "Mot de passe réinitialisé", ar: "تم إعادة تعيين كلمة المرور" },
  passwordResetSuccessDescription: { fr: "Votre mot de passe a été modifié avec succès. Vous pouvez maintenant vous connecter.", ar: "تم تغيير كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول." },
  backToLogin: { fr: "Retour à la connexion", ar: "العودة إلى تسجيل الدخول" },
  enterEmail: { fr: "Entrez votre email", ar: "أدخل بريدك الإلكتروني" },
  emailNotFound: { fr: "Aucun compte trouvé avec cet email", ar: "لم يتم العثور على حساب بهذا البريد الإلكتروني" },
  wantToCreateAccount: { fr: "Voulez-vous créer un nouveau compte ?", ar: "هل تريد إنشاء حساب جديد؟" },
  createNewAccount: { fr: "Créer un compte", ar: "إنشاء حساب" },
  tryAnotherEmail: { fr: "Essayer un autre email", ar: "جرب بريد إلكتروني آخر" },
  secureReset: { fr: "Réinitialisation sécurisée", ar: "إعادة تعيين آمنة" },
  enterYourEmail: { fr: "Entrez l'email associé à votre compte", ar: "أدخل البريد الإلكتروني المرتبط بحسابك" },
  codeSentSuccess: { fr: "Code envoyé avec succès", ar: "تم إرسال الرمز بنجاح" },
  checkYourInbox: { fr: "Vérifiez votre boîte de réception", ar: "تحقق من صندوق الوارد" },
  createSecurePassword: { fr: "Créez un mot de passe sécurisé", ar: "أنشئ كلمة مرور آمنة" },
  passwordMinChars: { fr: "Au moins 6 caractères", ar: "6 أحرف على الأقل" },
  becomeDriver: { fr: "Devenir chauffeur", ar: "كن سائقاً" },
  joinAsDriver: { fr: "Rejoignez notre réseau de chauffeurs professionnels", ar: "انضم إلى شبكتنا من السائقين المحترفين" },
  admin: { fr: "Administration", ar: "الإدارة" },
  adminPanel: { fr: "Panneau d'administration", ar: "لوحة الإدارة" },
  driverVerification: { fr: "Vérification des chauffeurs", ar: "التحقق من السائقين" },
  all: { fr: "Tous", ar: "الكل" },
  rejected: { fr: "Rejeté", ar: "مرفوض" },
  noDriversFound: { fr: "Aucun chauffeur trouvé", ar: "لم يتم العثور على سائقين" },
  noDriversMatchingFilter: { fr: "Aucun chauffeur ne correspond à ce filtre", ar: "لا يوجد سائق يطابق هذا الفلتر" },
  driverDetails: { fr: "Détails du chauffeur", ar: "تفاصيل السائق" },
  driverInfo: { fr: "Informations du chauffeur", ar: "معلومات السائق" },
  noDocumentsUploaded: { fr: "Aucun document téléchargé", ar: "لم يتم رفع أي مستندات" },
  verificationNotes: { fr: "Notes de vérification", ar: "ملاحظات التحقق" },
  addNotesPlaceholder: { fr: "Ajouter des notes de vérification...", ar: "إضافة ملاحظات التحقق..." },
  approve: { fr: "Approuver", ar: "قبول" },
  driverApproved: { fr: "Chauffeur approuvé", ar: "تم قبول السائق" },
  driverRejected: { fr: "Chauffeur rejeté", ar: "تم رفض السائق" },
  driverCanNowAcceptOrders: { fr: "Le chauffeur peut maintenant accepter des commandes", ar: "يمكن للسائق الآن قبول الطلبات" },
  driverHasBeenRejected: { fr: "Le chauffeur a été rejeté", ar: "تم رفض السائق" },
  driverAlreadyVerified: { fr: "Ce chauffeur est déjà vérifié", ar: "هذا السائق موثق بالفعل" },
  error: { fr: "Erreur", ar: "خطأ" },
  failedToUpdateDriver: { fr: "Échec de la mise à jour du chauffeur", ar: "فشل في تحديث السائق" },
  verifiedDriver: { fr: "Chauffeur vérifié", ar: "سائق موثق" },
  loginAsAdmin: { fr: "Connexion admin", ar: "تسجيل دخول المسؤول" },
  adminCode: { fr: "Code admin", ar: "رمز المسؤول" },
  loadingMap: { fr: "Chargement de la carte...", ar: "جاري تحميل الخريطة..." },
  nearbyDrivers: { fr: "Chauffeurs à proximité", ar: "السائقون القريبون" },
  noNearbyDrivers: { fr: "Aucun chauffeur à proximité", ar: "لا يوجد سائقون قريبون" },
  yourPosition: { fr: "Votre position", ar: "موقعك" },
  driversAvailable: { fr: "chauffeurs disponibles", ar: "سائقون متاحون" },
  driversNearby: { fr: "chauffeurs proches", ar: "سائقون قريبون" },
  yourLocation: { fr: "Votre position", ar: "موقعك" },
  online: { fr: "En ligne", ar: "متصل" },
  liveTracking: { fr: "Suivi en direct", ar: "التتبع المباشر" },
  useExpoGo: { fr: "Ouvrez l'application Expo Go sur votre téléphone pour utiliser le suivi en direct.", ar: "افتح تطبيق Expo Go على هاتفك لاستخدام التتبع المباشر." },
  signature: { fr: "Signature du client", ar: "توقيع العميل" },
  signHere: { fr: "Signez ici", ar: "وقّع هنا" },
  clear: { fr: "Effacer", ar: "مسح" },
  deliveryNote: { fr: "Bon de livraison", ar: "سند التسليم" },
  noDocuments: { fr: "Aucun document", ar: "لا توجد مستندات" },
  generateDeliveryNote: { fr: "Générer le bon de livraison", ar: "إنشاء سند التسليم" },
  signatureRequired: { fr: "Signature requise", ar: "التوقيع مطلوب" },
  photoProofOfDelivery: { fr: "Photo preuve de livraison", ar: "صورة إثبات التسليم" },
  takePhotoOfDeliveredGoods: { fr: "Prenez une photo des marchandises livrées", ar: "التقط صورة للبضائع المسلمة" },
  clientSignatureRequired: { fr: "Signature du client requise", ar: "توقيع العميل مطلوب" },
  photoRequired: { fr: "Photo requise", ar: "الصورة مطلوبة" },
  chooseFromGallery: { fr: "Choisir de la galerie", ar: "اختيار من المعرض" },
  photoTaken: { fr: "Photo prise", ar: "تم التقاط الصورة" },
  cameraPermissionRequired: { fr: "Permission caméra requise", ar: "إذن الكاميرا مطلوب" },
  deliveryProof: { fr: "Preuve de livraison", ar: "إثبات التسليم" },
  photoOfDeliveredGoods: { fr: "Photo des marchandises livrées", ar: "صورة البضائع المسلمة" },
  clientSignature: { fr: "Signature du client", ar: "توقيع العميل" },
  confirmDelivery: { fr: "Confirmer la livraison", ar: "تأكيد التسليم" },
  deliveryConfirmed: { fr: "Livraison confirmée", ar: "تم تأكيد التسليم" },
  viewDeliveryNote: { fr: "Voir le bon de livraison", ar: "عرض سند التسليم" },
  pickupPoint: { fr: "Point de ramassage", ar: "نقطة الالتقاط" },
  dropoffPoint: { fr: "Point de livraison", ar: "نقطة التسليم" },
  estimatedArrival: { fr: "Arrivée estimée", ar: "الوصول المقدر" },
  trackDriver: { fr: "Suivre le chauffeur", ar: "تتبع السائق" },
  locationPermissionDenied: { fr: "Permission de localisation refusée", ar: "تم رفض إذن الموقع" },
  enableLocation: { fr: "Activer la localisation", ar: "تفعيل الموقع" },
  verificationRequired: { fr: "Vérification requise", ar: "التحقق مطلوب" },
  verificationRequiredMessage: { fr: "Vous devez être vérifié pour accepter des commandes", ar: "يجب أن تكون موثقاً لقبول الطلبات" },
  pendingVerificationMessage: { fr: "Votre compte est en cours de vérification. La validation prend généralement entre 24h et 48h. Vous pourrez accepter des commandes une fois vérifié.", ar: "حسابك قيد التحقق. عادة ما يستغرق التحقق بين 24 و 48 ساعة. ستتمكن من قبول الطلبات بمجرد التحقق." },
  verificationWaitTime: { fr: "Délai de vérification: 24-48h", ar: "مدة التحقق: 24-48 ساعة" },
  rejectedDriverNote: { fr: "Votre demande a été rejetée. Veuillez corriger les problèmes indiqués et soumettre à nouveau vos documents.", ar: "تم رفض طلبك. يرجى تصحيح المشاكل المشار إليها وإعادة تقديم مستنداتك." },
  verificationRejected: { fr: "Vérification rejetée", ar: "تم رفض التحقق" },
  rejectionReason: { fr: "Raison du rejet", ar: "سبب الرفض" },
  updateDocuments: { fr: "Modifier mes documents", ar: "تعديل مستنداتي" },
  updateDocumentsDescription: { fr: "Mettez à jour vos documents et soumettez-les à nouveau pour vérification.", ar: "قم بتحديث مستنداتك وأعد تقديمها للتحقق." },
  uploaded: { fr: "Téléchargé", ar: "تم الرفع" },
  notUploaded: { fr: "Non téléchargé", ar: "لم يتم الرفع" },
  submitForReview: { fr: "Soumettre pour vérification", ar: "إرسال للمراجعة" },
  documentsUpdatedSuccess: { fr: "Vos documents ont été soumis. La vérification prendra 24-48h.", ar: "تم تقديم مستنداتك. سيستغرق التحقق 24-48 ساعة." },
  documentsUpdateError: { fr: "Échec de la mise à jour des documents", ar: "فشل في تحديث المستندات" },
  failedToAcceptOrder: { fr: "Échec de l'acceptation de la commande", ar: "فشل في قبول الطلب" },
  liveUpdates: { fr: "Mises à jour en direct", ar: "تحديثات مباشرة" },
  polling: { fr: "Actualisation automatique", ar: "تحديث تلقائي" },
  nearbyOrders: { fr: "Commandes à proximité", ar: "الطلبات القريبة" },
  noNearbyOrders: { fr: "Aucune commande à proximité", ar: "لا توجد طلبات قريبة" },
  ok: { fr: "OK", ar: "حسناً" },
  welcomeBack: { fr: "Bon retour !", ar: "مرحبا بعودتك!" },
  signInToContinue: { fr: "Connectez-vous pour continuer", ar: "سجل دخولك للمتابعة" },
  chooseHowToUse: { fr: "Comment souhaitez-vous utiliser FAYAGE ?", ar: "كيف تريد استخدام فاياج؟" },
  fillDetailsBelow: { fr: "Remplissez les informations ci-dessous", ar: "املأ المعلومات أدناه" },
  enterAdminCode: { fr: "Entrez le code administrateur", ar: "أدخل رمز المسؤول" },
  hello: { fr: "Bonjour", ar: "مرحبا" },
  needTransport: { fr: "Besoin de transport ?", ar: "هل تحتاج إلى نقل؟" },
  createNewRequest: { fr: "Créer une nouvelle demande", ar: "إنشاء طلب جديد" },
  yourRequests: { fr: "Vos demandes", ar: "طلباتك" },
  seeAll: { fr: "Voir tout", ar: "رؤية الكل" },
  noRequestsYet: { fr: "Aucune demande pour le moment", ar: "لا توجد طلبات بعد" },
  createFirstRequest: { fr: "Créez votre première demande de transport", ar: "أنشئ طلب النقل الأول" },
  quickStats: { fr: "Statistiques rapides", ar: "إحصائيات سريعة" },
  totalRequests: { fr: "Total des demandes", ar: "إجمالي الطلبات" },
  completedRequests: { fr: "Demandes terminées", ar: "الطلبات المكتملة" },
  avgRating: { fr: "Note moyenne", ar: "التقييم المتوسط" },
  awaitingApproval: { fr: "En attente de validation", ar: "في انتظار الموافقة" },
  driverWantsToAccept: { fr: "Un chauffeur souhaite prendre votre commande", ar: "سائق يريد قبول طلبك" },
  driversWantToAccept: { fr: "Chauffeurs intéressés", ar: "السائقون المهتمون" },
  waitingForApproval: { fr: "En attente d'approbation", ar: "في انتظار الموافقة" },
  driverRejectedNotification: { fr: "Le client a choisi un autre chauffeur", ar: "اختار العميل سائقًا آخر" },
  viewDriverProfile: { fr: "Voir le profil du chauffeur", ar: "عرض ملف السائق" },
  approveDriver: { fr: "Accepter ce chauffeur", ar: "قبول هذا السائق" },
  rejectDriver: { fr: "Refuser ce chauffeur", ar: "رفض هذا السائق" },
  driverProfile: { fr: "Profil du chauffeur", ar: "ملف السائق" },
  reviews: { fr: "Avis", ar: "التقييمات" },
  noReviewsYet: { fr: "Aucun avis pour le moment", ar: "لا توجد تقييمات بعد" },
  basedOnRatings: { fr: "Basé sur {count} avis", ar: "بناءً على {count} تقييم" },
  aboutDriver: { fr: "À propos du chauffeur", ar: "عن السائق" },
  vehicle: { fr: "Véhicule", ar: "المركبة" },
  close: { fr: "Fermer", ar: "إغلاق" },
  moreReviews: { fr: "autres avis", ar: "تقييمات أخرى" },
  driverAcceptedNotification: { fr: "a accepté votre demande!", ar: "قبل طلبك!" },
  clientApprovedNotification: { fr: "Le client a approuvé votre candidature!", ar: "وافق العميل على ترشيحك!" },
  newOrderNotification: { fr: "Nouvelle demande de transport disponible!", ar: "طلب نقل جديد متاح!" },
  driverEnRoute: { fr: "Chauffeur en route", ar: "السائق في الطريق" },
  deliveryImminent: { fr: "Livraison imminente", ar: "التسليم وشيك" },
  status: { fr: "Statut", ar: "الحالة" },
  tracking: { fr: "Suivi", ar: "تتبع" },
  waitingForDriverLocation: { fr: "En attente de la position du chauffeur...", ar: "في انتظار موقع السائق..." },
  cancelOrder: { fr: "Annuler la commande", ar: "إلغاء الطلب" },
  confirmCancelOrder: { fr: "Êtes-vous sûr de vouloir annuler cette commande ?", ar: "هل أنت متأكد من إلغاء هذا الطلب؟" },
  editProfile: { fr: "Modifier le profil", ar: "تعديل الملف الشخصي" },
  updateProfile: { fr: "Mettre à jour le profil", ar: "تحديث الملف الشخصي" },
  currentPassword: { fr: "Mot de passe actuel", ar: "كلمة المرور الحالية" },
  profileUpdated: { fr: "Profil mis à jour avec succès", ar: "تم تحديث الملف الشخصي بنجاح" },
  emailUpdateSuccess: { fr: "Email mis à jour avec succès", ar: "تم تحديث البريد الإلكتروني بنجاح" },
  passwordUpdateSuccess: { fr: "Mot de passe mis à jour avec succès", ar: "تم تحديث كلمة المرور بنجاح" },
  saveChanges: { fr: "Enregistrer", ar: "حفظ" },
  faq: { fr: "Questions fréquentes", ar: "الأسئلة الشائعة" },
  contactSupport: { fr: "Contacter le support", ar: "الاتصال بالدعم" },
  howToCreateRequest: { fr: "Comment créer une demande de transport ?", ar: "كيف أنشئ طلب نقل؟" },
  howToCreateRequestAnswer: { fr: "Allez dans l'onglet Accueil, appuyez sur 'Créer une demande', remplissez les détails et soumettez.", ar: "اذهب إلى تبويب الرئيسية، اضغط على 'إنشاء طلب'، املأ التفاصيل وأرسل." },
  howToTrack: { fr: "Comment suivre ma livraison ?", ar: "كيف أتتبع توصيلتي؟" },
  howToTrackAnswer: { fr: "Utilisez l'onglet Suivi pour voir en temps réel où se trouve votre chauffeur.", ar: "استخدم تبويب التتبع لرؤية موقع سائقك في الوقت الفعلي." },
  howToRate: { fr: "Comment noter un chauffeur ?", ar: "كيف أقيم السائق؟" },
  howToRateAnswer: { fr: "Après la livraison, une invite de notation apparaîtra. Vous pouvez aussi le faire depuis l'historique.", ar: "بعد التوصيل، ستظهر نافذة التقييم. يمكنك أيضاً القيام بذلك من السجل." },
  howToBecomeDriver: { fr: "Comment devenir chauffeur ?", ar: "كيف أصبح سائقاً؟" },
  howToBecomeDriverAnswer: { fr: "Inscrivez-vous comme chauffeur, téléchargez vos documents et attendez la vérification.", ar: "سجل كسائق، ارفع مستنداتك وانتظر التحقق." },
  paymentQuestion: { fr: "Quels sont les modes de paiement ?", ar: "ما هي طرق الدفع؟" },
  paymentAnswer: { fr: "Actuellement, le paiement en espèces est accepté. D'autres méthodes seront bientôt disponibles.", ar: "حالياً، الدفع نقداً مقبول. طرق أخرى ستتوفر قريباً." },
  sendEmail: { fr: "Envoyer un email", ar: "إرسال بريد إلكتروني" },
  callUs: { fr: "Appelez-nous", ar: "اتصل بنا" },
  supportEmail: { fr: "FAYAG.APP@GMAIL.COM", ar: "FAYAG.APP@GMAIL.COM" },
  supportPhone: { fr: "0638563712", ar: "0638563712" },
  aboutApp: { fr: "À propos de FAYAGE", ar: "عن فاياج" },
  appVersion: { fr: "Version 1.0.0", ar: "الإصدار 1.0.0" },
  termsAndConditions: { fr: "Conditions d'utilisation", ar: "شروط الاستخدام" },
  privacyPolicy: { fr: "Politique de confidentialité", ar: "سياسة الخصوصية" },
  newEmail: { fr: "Nouvel email", ar: "البريد الإلكتروني الجديد" },
  verifyNewEmail: { fr: "Vérifier le nouvel email", ar: "التحقق من البريد الجديد" },
  changePassword: { fr: "Changer le mot de passe", ar: "تغيير كلمة المرور" },
  favoriteDrivers: { fr: "Chauffeurs favoris", ar: "السائقون المفضلون" },
  addToFavorites: { fr: "Ajouter aux favoris", ar: "إضافة إلى المفضلة" },
  removeFromFavorites: { fr: "Retirer des favoris", ar: "إزالة من المفضلة" },
  noFavoriteDrivers: { fr: "Aucun chauffeur favori", ar: "لا يوجد سائقون مفضلون" },
  noFavoriteDriversDesc: { fr: "Ajoutez des chauffeurs aux favoris pour les retrouver facilement", ar: "أضف السائقين إلى المفضلة للعثور عليهم بسهولة" },
  savedDrivers: { fr: "chauffeurs enregistrés", ar: "سائقون محفوظون" },
  removeFavorite: { fr: "Retirer des favoris", ar: "إزالة من المفضلة" },
  confirmRemoveFavorite: { fr: "Voulez-vous retirer des favoris", ar: "هل تريد إزالة من المفضلة" },
  remove: { fr: "Retirer", ar: "إزالة" },
  addFavoriteDriversDesc: { fr: "Ajoutez des chauffeurs à vos favoris pour les demander directement", ar: "أضف سائقين إلى المفضلة لطلبهم مباشرة" },
  requestFavoriteDriver: { fr: "Demander ce chauffeur", ar: "طلب هذا السائق" },
  preferredDriver: { fr: "Chauffeur préféré", ar: "السائق المفضل" },
  selectPreferredDriver: { fr: "Choisir un chauffeur préféré", ar: "اختيار سائق مفضل" },
  noPreference: { fr: "Aucune préférence", ar: "بدون تفضيل" },
  scheduledDelivery: { fr: "Livraison programmée", ar: "توصيل مجدول" },
  scheduleForLater: { fr: "Programmer pour plus tard", ar: "جدولة لوقت لاحق" },
  immediateDelivery: { fr: "Livraison immédiate", ar: "توصيل فوري" },
  selectDateTime: { fr: "Sélectionner date et heure", ar: "اختر التاريخ والوقت" },
  scheduledFor: { fr: "Programmé pour", ar: "مجدول ل" },
  driverNotified: { fr: "Le chauffeur sera notifié", ar: "سيتم إخطار السائق" },
  pushNotificationsEnabled: { fr: "Notifications push activées", ar: "تم تفعيل الإشعارات" },
  pushNotificationsDisabled: { fr: "Notifications push désactivées", ar: "الإشعارات معطلة" },
  enableNotifications: { fr: "Activer les notifications", ar: "تفعيل الإشعارات" },
  notificationNewJob: { fr: "Nouvelle mission disponible", ar: "مهمة جديدة متاحة" },
  notificationOrderAccepted: { fr: "Votre commande a été acceptée", ar: "تم قبول طلبك" },
  notificationOrderDelivered: { fr: "Votre commande a été livrée", ar: "تم توصيل طلبك" },
  markAsFavorite: { fr: "Marquer comme favori", ar: "وضع علامة كمفضل" },
  favoriteDriverAdded: { fr: "Chauffeur ajouté aux favoris", ar: "تم إضافة السائق إلى المفضلة" },
  favoriteDriverRemoved: { fr: "Chauffeur retiré des favoris", ar: "تم إزالة السائق من المفضلة" },
  referralCodeOptional: { fr: "Code de parrainage (optionnel)", ar: "رمز الإحالة (اختياري)" },
  enterReferralCode: { fr: "Entrez le code de parrainage", ar: "أدخل رمز الإحالة" },
  referredBy: { fr: "Parrainé par", ar: "أحيل بواسطة" },
  invalidReferralCode: { fr: "Code de parrainage invalide", ar: "رمز الإحالة غير صالح" },
  referralProgram: { fr: "Programme de parrainage", ar: "برنامج الإحالة" },
  yourReferralCode: { fr: "Votre code de parrainage", ar: "رمز الإحالة الخاص بك" },
  shareCode: { fr: "Partager le code", ar: "مشاركة الرمز" },
  copyCode: { fr: "Copier le code", ar: "نسخ الرمز" },
  codeCopied: { fr: "Code copié!", ar: "تم نسخ الرمز!" },
  inviteFriends: { fr: "Invitez vos amis", ar: "ادعُ أصدقاءك" },
  inviteFriendsDesc: { fr: "Partagez votre code avec vos amis et gagnez des récompenses", ar: "شارك رمزك مع أصدقائك واكسب مكافآت" },
  referralRewards: { fr: "Récompenses", ar: "المكافآت" },
  youEarn: { fr: "Vous gagnez", ar: "تكسب" },
  friendEarns: { fr: "Votre ami gagne", ar: "يكسب صديقك" },
  totalReferrals: { fr: "Total des parrainages", ar: "إجمالي الإحالات" },
  completedReferrals: { fr: "Parrainages réussis", ar: "الإحالات الناجحة" },
  pendingReferrals: { fr: "Parrainages en attente", ar: "الإحالات المعلقة" },
  rewardBalance: { fr: "Solde des récompenses", ar: "رصيد المكافآت" },
  referralHistory: { fr: "Historique des parrainages", ar: "سجل الإحالات" },
  noReferralsYet: { fr: "Aucun parrainage pour le moment", ar: "لا توجد إحالات بعد" },
  startInviting: { fr: "Commencez à inviter vos amis!", ar: "ابدأ بدعوة أصدقائك!" },
  referralStatusPending: { fr: "En attente", ar: "قيد الانتظار" },
  referralStatusCompleted: { fr: "Réussi", ar: "ناجح" },
  howItWorks: { fr: "Comment ça marche", ar: "كيف يعمل" },
  step1Title: { fr: "Partagez votre code", ar: "شارك رمزك" },
  step1Desc: { fr: "Envoyez votre code unique à vos amis", ar: "أرسل رمزك الفريد إلى أصدقائك" },
  step2Title: { fr: "Ami s'inscrit", ar: "يسجل صديقك" },
  step2Desc: { fr: "Votre ami utilise le code lors de l'inscription", ar: "يستخدم صديقك الرمز عند التسجيل" },
  step3Title: { fr: "Gagnez des récompenses", ar: "اكسب مكافآت" },
  step3Desc: { fr: "Recevez vos récompenses après la première commande", ar: "احصل على مكافآتك بعد الطلب الأول" },
  messages: { fr: "Messages", ar: "الرسائل" },
  conversations: { fr: "conversations", ar: "محادثات" },
  noConversations: { fr: "Aucune conversation", ar: "لا توجد محادثات" },
  noConversationsDesc: { fr: "Vos conversations avec les chauffeurs et clients apparaîtront ici", ar: "ستظهر محادثاتك مع السائقين والعملاء هنا" },
  noMessages: { fr: "Commencer une conversation", ar: "ابدأ محادثة" },
  yesterday: { fr: "Hier", ar: "أمس" },
  eta: { fr: "Arrivée estimée", ar: "الوصول المقدر" },
  etaMinutes: { fr: "min", ar: "دقيقة" },
  etaCalculating: { fr: "Calcul...", ar: "جاري الحساب..." },
  etaUnavailable: { fr: "Non disponible", ar: "غير متوفر" },
  arrivingIn: { fr: "Arrivée dans", ar: "الوصول خلال" },
  distanceRemaining: { fr: "Distance restante", ar: "المسافة المتبقية" },
  toPickup: { fr: "au ramassage", ar: "إلى الاستلام" },
  toDelivery: { fr: "à la livraison", ar: "إلى التسليم" },
  
  // Announcements
  announcements: { fr: "Annonces", ar: "الإعلانات" },
  announcementTitle: { fr: "Titre", ar: "العنوان" },
  announcementMessage: { fr: "Message", ar: "الرسالة" },
  announcementType: { fr: "Type", ar: "النوع" },
  announcementInfo: { fr: "Information", ar: "معلومات" },
  announcementWarning: { fr: "Avertissement", ar: "تحذير" },
  announcementUrgent: { fr: "Urgent", ar: "عاجل" },
  targetAudience: { fr: "Audience cible", ar: "الجمهور المستهدف" },
  audienceAll: { fr: "Tous", ar: "الجميع" },
  audienceClients: { fr: "Clients", ar: "العملاء" },
  audienceDrivers: { fr: "Chauffeurs", ar: "السائقين" },
  isActive: { fr: "Actif", ar: "نشط" },
  expiresAt: { fr: "Expire le", ar: "ينتهي في" },
  noExpiration: { fr: "Pas d'expiration", ar: "بدون انتهاء" },
  createAnnouncement: { fr: "Créer une annonce", ar: "إنشاء إعلان" },
  editAnnouncement: { fr: "Modifier l'annonce", ar: "تعديل الإعلان" },
  deleteAnnouncement: { fr: "Supprimer l'annonce", ar: "حذف الإعلان" },
  noAnnouncements: { fr: "Aucune annonce", ar: "لا توجد إعلانات" },
  announcementCreated: { fr: "Annonce créée", ar: "تم إنشاء الإعلان" },
  announcementUpdated: { fr: "Annonce modifiée", ar: "تم تحديث الإعلان" },
  announcementDeleted: { fr: "Annonce supprimée", ar: "تم حذف الإعلان" },
  confirmDeleteAnnouncement: { fr: "Voulez-vous vraiment supprimer cette annonce?", ar: "هل تريد حقاً حذف هذا الإعلان؟" },
  enterTitle: { fr: "Entrez le titre...", ar: "أدخل العنوان..." },
  enterMessage: { fr: "Entrez le message...", ar: "أدخل الرسالة..." },
  selectType: { fr: "Sélectionner le type", ar: "اختر النوع" },
  selectAudience: { fr: "Sélectionner l'audience", ar: "اختر الجمهور" },
  newAnnouncement: { fr: "Nouvelle annonce", ar: "إعلان جديد" },

  // Payment flow
  waitingForPayment: { fr: "En attente de paiement", ar: "في انتظار الدفع" },
  paymentInstructions: { fr: "Instructions de paiement", ar: "تعليمات الدفع" },
  paymentReference: { fr: "Référence de paiement", ar: "مرجع الدفع" },
  paymentAmount: { fr: "Montant à payer", ar: "المبلغ المطلوب" },
  paymentMethods: { fr: "Modes de paiement disponibles", ar: "طرق الدفع المتاحة" },
  paymentReceiver: { fr: "Bénéficiaire", ar: "المستفيد" },
  paymentReceiverPhone: { fr: "Numéro du bénéficiaire", ar: "رقم المستفيد" },
  uploadProof: { fr: "Joindre la preuve de paiement", ar: "رفع إثبات الدفع" },
  proofImage: { fr: "Reçu (photo obligatoire)", ar: "الإيصال (صورة مطلوبة)" },
  transactionRef: { fr: "Référence de transaction (optionnel)", ar: "مرجع المعاملة (اختياري)" },
  enterTransactionRef: { fr: "Ex: 12345678", ar: "مثال: 12345678" },
  submitProof: { fr: "Soumettre la preuve", ar: "إرسال الإثبات" },
  proofSubmitted: { fr: "Preuve soumise avec succès. En attente de vérification.", ar: "تم رفع الإثبات بنجاح. في انتظار التحقق." },
  paymentPending: { fr: "En attente de vérification", ar: "في انتظار التحقق" },
  paymentAccepted: { fr: "Paiement vérifié", ar: "تم التحقق من الدفع" },
  paymentRejected: { fr: "Preuve refusée", ar: "تم رفض الإثبات" },
  paymentRejectedDesc: { fr: "Votre preuve de paiement a été refusée. Soumettez une nouvelle preuve.", ar: "تم رفض إثبات الدفع الخاص بك. يرجى تقديم إثبات جديد." },
  resubmitProof: { fr: "Soumettre une nouvelle preuve", ar: "إرسال إثبات جديد" },
  copyReference: { fr: "Copier la référence", ar: "نسخ المرجع" },
  referenceCopied: { fr: "Référence copiée", ar: "تم نسخ المرجع" },
  wafacash: { fr: "Wafacash", ar: "وافاكاش" },
  cashPlus: { fr: "Cash Plus", ar: "كاش بلوس" },
  paymentNote: { fr: "Important: Mentionnez la référence lors du virement", ar: "مهم: اذكر المرجع عند التحويل" },
  contactLockedUntilPayment: { fr: "Contact disponible après confirmation du paiement", ar: "جهة الاتصال متاحة بعد تأكيد الدفع" },
  confirmDelivery: { fr: "Confirmer la livraison", ar: "تأكيد التسليم" },
  confirmDeliveryDesc: { fr: "Avez-vous bien reçu votre livraison?", ar: "هل استلمت طلبك بالفعل؟" },
  deliveryConfirmed: { fr: "Livraison confirmée. Merci!", ar: "تم تأكيد التسليم. شكراً!" },
  orderCompleted: { fr: "Commande terminée", ar: "تم إكمال الطلب" },

  payNow: { fr: "Payer maintenant", ar: "ادفع الآن" },
  availableAfterPayment: { fr: "Disponible après paiement", ar: "متاح بعد الدفع" },

  // Admin Payments
  paymentsManagement: { fr: "Gestion des paiements", ar: "إدارة المدفوعات" },
  payments: { fr: "Paiements", ar: "المدفوعات" },
  allPayments: { fr: "Tous les paiements", ar: "كل المدفوعات" },
  pendingPayments: { fr: "En attente", ar: "قيد الانتظار" },
  acceptPayment: { fr: "Accepter", ar: "قبول" },
  rejectPayment: { fr: "Refuser", ar: "رفض" },
  paymentStatus: { fr: "Statut", ar: "الحالة" },
  pending_upload: { fr: "Preuve manquante", ar: "الإيصال مفقود" },
  pending_review: { fr: "En cours de vérification", ar: "قيد المراجعة" },
  commissionRate: { fr: "Commission", ar: "العمولة" },
  driverEarning: { fr: "Gain chauffeur", ar: "أرباح السائق" },
  viewProof: { fr: "Voir la preuve", ar: "عرض الإثبات" },
  noPayments: { fr: "Aucun paiement", ar: "لا توجد مدفوعات" },
  noPaymentsDesc: { fr: "Les paiements apparaîtront ici", ar: "ستظهر المدفوعات هنا" },

  // Driver wallet
  wallet: { fr: "Portefeuille", ar: "المحفظة" },
  myWallet: { fr: "Mon portefeuille", ar: "محفظتي" },
  walletBalance: { fr: "Solde disponible", ar: "الرصيد المتاح" },
  availableBalance: { fr: "SOLDE DISPONIBLE", ar: "الرصيد المتاح" },
  totalEarnings: { fr: "Total des gains", ar: "إجمالي الأرباح" },
  totalCommission: { fr: "Commission totale", ar: "إجمالي العمولات" },
  totalEarned: { fr: "Total gagné", ar: "إجمالي المكاسب" },
  withdrawal: { fr: "Retrait", ar: "سحب" },
  requestWithdrawal: { fr: "Demander un retrait", ar: "طلب سحب" },
  withdrawalProcessing: { fr: "Demande en cours de traitement...", ar: "الطلب قيد المعالجة..." },
  completeDeliveriesForBalance: { fr: "Complétez des livraisons pour accumuler des gains", ar: "أكمل عمليات التوصيل لتجميع الأرباح" },
  withdrawalSuccessful: { fr: "Réussi", ar: "ناجح" },
  withdrawalHistory: { fr: "Historique des retraits", ar: "سجل السحوبات" },
  withdrawalAmount: { fr: "Montant du retrait", ar: "مبلغ السحب" },
  beneficiaryName: { fr: "Nom complet du bénéficiaire", ar: "الاسم الكامل للمستفيد" },
  yourFullName: { fr: "Votre nom complet", ar: "اسمك الكامل" },
  wafacashDesc: { fr: "Transfert instantané via WafaCash", ar: "تحويل فوري عبر وافاكاش" },
  cashplusDesc: { fr: "Retrait en agence CashPlus", ar: "سحب في وكالة كاش بلوس" },
  paymentAccountNote: { fr: "Le paiement sera envoyé sur votre compte enregistré", ar: "سيتم إرسال الدفعة إلى حسابك المسجل" },
  sendRequest: { fr: "Envoyer la demande", ar: "إرسال الطلب" },
  paymentCodeReceived: { fr: "Code de paiement reçu !", ar: "تم استلام رمز الدفع!" },
  confirmReception: { fr: "Confirmer la réception", ar: "تأكيد الاستلام" },
  noWithdrawals: { fr: "Aucun retrait effectué", ar: "لا توجد سحوبات" },
  noWithdrawalsDesc: { fr: "Vos demandes de retrait apparaîtront ici", ar: "طلبات السحب ستظهر هنا" },
  withdrawalSent: { fr: "Envoyé", ar: "تم الإرسال" },
  withdrawalConfirmed: { fr: "Confirmé", ar: "مؤكد" },
  withdrawalRequestSent: { fr: "Demande envoyée ✅", ar: "تم إرسال الطلب ✅" },
  withdrawalSubmitError: { fr: "Impossible de soumettre la demande", ar: "تعذر تقديم الطلب" },
  copy: { fr: "Copier", ar: "نسخ" },
  copied: { fr: "Copié", ar: "تم النسخ" },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = "@fayage_language";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("fr");

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (savedLanguage === "ar" || savedLanguage === "fr") {
        setLanguageState(savedLanguage);
      }
    } catch (error) {
      console.error("Error loading language:", error);
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
      setLanguageState(lang);
    } catch (error) {
      console.error("Error saving language:", error);
    }
  };

  const t = (key: string): string => {
    const translation = translations[key];
    if (!translation) {
      return key;
    }
    return translation[language] || key;
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
